# Generated by Django 2.1.7 on 2019-04-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_diabetes',
        ),
    ]
