# Generated by Django 2.1.7 on 2019-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190417_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_diabetec',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_activetylevel',
        ),
        migrations.AddField(
            model_name='users',
            name='is_diabetic',
            field=models.IntegerField(blank=True, db_column='is-diabetic', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_activitylevel',
            field=models.IntegerField(blank=True, db_column='user-activitylevel', null=True),
        ),
    ]
