# Generated by Django 2.1.7 on 2019-06-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190618_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsCategories',
            fields=[
                ('categ_id', models.AutoField(primary_key=True, serialize=False)),
                ('categ_name', models.CharField(blank=True, max_length=45, null=True)),
                ('sub_categ', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients_categories',
                'managed': False,
            },
        ),
    ]
