# Generated by Django 2.1.7 on 2019-06-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ingredientscategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={},
        ),
    ]
