# Generated by Django 2.1.7 on 2019-06-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190622_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='users_user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='meals',
            name='categ',
            field=models.ForeignKey(db_column='categ-id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.FoodCategroies'),
        ),
    ]
