# Generated by Django 2.1.7 on 2019-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190626_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='saved_meals',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_weight',
            field=models.IntegerField(blank=True, db_column='user-weight', null=True),
        ),
    ]
