# Generated by Django 2.1.7 on 2019-06-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_meals_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='categ_id',
            field=models.ForeignKey(db_column='categ-id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.FoodCategroies'),
        ),
        migrations.AddField(
            model_name='users',
            name='saved_meals',
            field=models.TextField(blank=True, db_column='saved-meals', null=True),
        ),
    ]
