# Generated by Django 2.1.7 on 2019-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190628_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.TextField(blank=True, db_column='user-image', null=True),
        ),
    ]
